markdown: kramdown
kramdown:
    entity_output: symbolic
    smart_quotes: lsquo,rsquo,ldquo,rdquo
highlighter: rouge
lsi: true
url: http://www.foldl.me

permalink: /:year/:title/
paginate: 20
paginate_path: /posts/page:num
