markdown: kramdown
kramdown:
    entity_output: symbolic
    smart_quotes: lsquo,rsquo,ldquo,rdquo
highlighter: rouge
lsi: true
url: http://www.foldl.me

papers:
    - id: ccn2018
      title: Does the brain represent words? An evaluation of brain decoding studies of language understanding
      authors: "{Jon Gauthier and Anna Ivanova}"
      date: September 2018
      venue: 2018 Conference on Cognitive Computational Neuroscience
      code: https://github.com/hans/nn-decoding
      url: https://arxiv.org/pdf/1806.00591.pdf
      bibtex: true
      links:
          - href: /uploads/2018/ccn2018-poster.pdf
            title: poster
    - id: cogsci2018
      title: Word learning and the acquisition of syntactic–semantic overhypotheses
      authors: Jon Gauthier, Roger Levy, and Joshua B. Tenenbaum
      date: February 2018
      venue: Cognitive Science 2018
      url: https://arxiv.org/pdf/1805.04988.pdf
      bibtex: true
    - id: acl-robonlp2017
      title: Are distributional representations ready for the real world? Evaluating word vectors for grounded perceptual meaning
      authors: Li Lucy and Jon Gauthier
      date: May 2016
      venue: ACL 2017 Workshop on Language Grounding for Robotics
      url: https://arxiv.org/pdf/1705.11168.pdf
      bibtex: true
      code: https://github.com/lucy3/graphs-embeddings
    - id: nips-main2016
      title: A paradigm for situated and goal-driven language learning
      authors: Jon Gauthier and Igor Mordatch
      date: October 2016
      venue: NIPS 2016 Machine Intelligence Workshop
      url: https://arxiv.org/pdf/1610.03585v1.pdf
      bibtex: true
      links:
          - href: /2016/situated-language-learning
            title: related blog post
          - href: https://docs.google.com/presentation/d/1PqMCUdqz3-GU5V_Cj6afD05-BtF2KMRyTlPyuOw2xCc/edit?usp=sharing
            title: slides
    - id: acl2016
      title: A fast unified model for parsing and sentence understanding
      authors: "{Sam Bowman, Jon Gauthier}, Raghav Gupta, Abhinav Rastogi, Christopher D. Manning, and Christopher Potts"
      date: 2016
      venue: ACL 2016
      url: http://arxiv.org/pdf/1603.06021.pdf
      code: https://github.com/stanfordnlp/spinn
      bibtex: true
    - id: tr-cgans
      title: Conditional generative adversarial networks for convolutional face generation
      authors: Jon Gauthier
      date: March 2015
      venue: Technical report, March 2015
      code: https://github.com/hans/adversarial
      bibtex: true
    - id: iclr2015_draft
      title: Exploiting long-distance context in transition-based dependency parsing with recurrent neural networks
      authors: Jon Gauthier, Danqi Chen, and Christopher D. Manning
      date: 2014
      venue: Preprint, 2014

permalink: /:year/:title/
paginate: 20
paginate_path: /posts/page:num
