markdown: kramdown
kramdown:
    entity_output: symbolic
    smart_quotes: lsquo,rsquo,ldquo,rdquo
highlighter: rouge
lsi: true
url: http://www.foldl.me

papers:
    - id: acl2020_long
      title: A systematic assessment of syntactic generalization in neural language models
      authors: Jennifer Hu, Jon Gauthier, Peng Qian, Ethan Wilcox, and Roger Levy
      date: Spring 2019
      venue: ACL 2020
      code: https://github.com/cpllab/syntactic-generalization
      bibtex: acl2020_long.bib
    - id: bbs2019
      title: From mental representations to neural codes&#58; A multilevel approach
      authors: Jon Gauthier, João Loula, Eli Pollock, Tyler Brooke Wilson, and Catherine Wong
      date: November 2019
      venue: Behavioral and Brain Sciences
      url: https://www-cambridge-org.libproxy.mit.edu/core/journals/behavioral-and-brain-sciences/article/from-mental-representations-to-neural-codes-a-multilevel-approach/484046589CE54F9DF872D602A70683F2
      bibtex: bbs2019.bib
    - id: emnlp2019
      title: "Linking human and artificial neural representations of language"
      authors: Jon Gauthier and Roger Levy
      date: October 2019
      venue: EMNLP 2019
      code: https://github.com/hans/nn-decoding/tree/emnlp2019-final
      url: https://arxiv.org/abs/1910.01244
      bibtex: emnlp2019.bib
    - id: cogsci2019
      title: A rational model of syntactic bootstrapping
      authors: Jon Gauthier, Roger Levy, and Joshua B. Tenenbaum
      date: February 2019
      venue: Cognitive Science 2019
      bibtex: cogsci2019.bib
      links:
          - href: /uploads/2019/cogsci2019-poster.pdf
            title: poster
    - id: cogsci2019-jchu
      title: Query-guided visual search
      authors: Junyi Chu, Jon Gauthier, Joshua B. Tenenbaum, Roger Levy, and Laura Schulz
      date: February 2019
      venue: Cognitive Science 2019
    - id: ccn2018
      title: Does the brain represent words? An evaluation of brain decoding studies of language understanding
      authors: "{Jon Gauthier and Anna Ivanova}"
      date: September 2018
      venue: 2018 Conference on Cognitive Computational Neuroscience
      code: https://github.com/hans/nn-decoding/tree/ccn2018
      url: https://arxiv.org/abs/1806.00591
      bibtex: ccn2018.bib
      links:
          - href: /uploads/2018/ccn2018-poster.pdf
            title: poster
    - id: cogsci2018
      title: Word learning and the acquisition of syntactic–semantic overhypotheses
      authors: Jon Gauthier, Roger Levy, and Joshua B. Tenenbaum
      date: February 2018
      venue: Cognitive Science 2018
      url: https://arxiv.org/pdf/1805.04988.pdf
      bibtex: cogsci2018.bib
    - id: acl-robonlp2017
      title: Are distributional representations ready for the real world? Evaluating word vectors for grounded perceptual meaning
      authors: Li Lucy and Jon Gauthier
      date: May 2016
      venue: ACL 2017 Workshop on Language Grounding for Robotics
      url: https://arxiv.org/pdf/1705.11168.pdf
      bibtex: acl-robonlp2017.bib
      code: https://github.com/lucy3/graphs-embeddings
    - id: nips-main2016
      title: A paradigm for situated and goal-driven language learning
      authors: Jon Gauthier and Igor Mordatch
      date: October 2016
      venue: NIPS 2016 Machine Intelligence Workshop
      url: https://arxiv.org/pdf/1610.03585v1.pdf
      bibtex: nips-main2016.bib
      links:
          - href: /2016/situated-language-learning
            title: related blog post
          - href: https://docs.google.com/presentation/d/1PqMCUdqz3-GU5V_Cj6afD05-BtF2KMRyTlPyuOw2xCc/edit?usp=sharing
            title: slides
    - id: acl2016
      title: A fast unified model for parsing and sentence understanding
      authors: "{Sam Bowman, Jon Gauthier}, Raghav Gupta, Abhinav Rastogi, Christopher D. Manning, and Christopher Potts"
      date: 2016
      venue: ACL 2016
      url: http://arxiv.org/pdf/1603.06021.pdf
      code: https://github.com/stanfordnlp/spinn
      bibtex: acl2016.bib
    - id: tr-cgans
      title: Conditional generative adversarial networks for convolutional face generation
      authors: Jon Gauthier
      date: March 2015
      venue: Technical report, March 2015
      code: https://github.com/hans/adversarial
      bibtex: tr-cgans.bib
    - id: iclr2015_draft
      title: Exploiting long-distance context in transition-based dependency parsing with recurrent neural networks
      authors: Jon Gauthier, Danqi Chen, and Christopher D. Manning
      date: 2014
      venue: Preprint, 2014

permalink: /:year/:title/
paginate: 20
paginate_path: /posts/page:num
